### ISSUE TITLE
OracleJava7 Override help

### ISSUE THREAD

**Issue by justinrummel** [homebysix/auto-update-magic#10]
I'm trying to make a OracleJava7 Overide similar to your AdobeFlashPlayer, however, I'm getting the following error once in the JSSImporter section:

``` bash
JSSImporter
JSSImporter: Category type: category-'Digital Media' already exists according to JSS, moving on...
JSSImporter: Category type: policy_category-'Auto Update' already exists according to JSS, moving on...
JSSImporter: Pkg-object already exists according to JSS, moving on...
JSSImporter: Package upload not needed.
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 1469, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 1463, in main
    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 1287, in run_recipes
    autopackager.process(recipe)
  File "/Library/AutoPkg/autopkglib/__init__.py", line 466, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 295, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 622, in main
    self.extattrs = self.handle_extension_attributes()
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 490, in handle_extension_attributes
    added_env="jss_extension_attribute_updated")
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 456, in _update_or_create_new
    recipe_object.save()
  File "/Library/Python/2.7/site-packages/python_jss-0.5.3-py2.7.egg/jss/jss.py", line 605, in save
    "Object Conflict! If trying to post a new "
jss.exceptions.JSSPostError: Object Conflict! If trying to post a new object, look for name conflict and delete.
````

OracleJava7.jss.recipe: https://gist.github.com/justinrummel/7b94c9fc98e868af3b86
OracleJava7ExtensionAttribute.xml: https://gist.github.com/justinrummel/5b43d941499c76fdabf4 
OracleJava7PolicyTemplate.xml: https://gist.github.com/justinrummel/7b4b316657ed0909059c 
OracleJava7SmartGroupTemplate.xml: https://gist.github.com/justinrummel/a1bfeb669c0240ea56a5

**Comment by homebysix** [comment]
Hi @justinrummel — what happens if you delete the Java package (or the package object, if the file itself is "missing") from the JSS, and then running the recipe again?

Are you uploading to a file share distribution point, or a JDS?

You may want to upgrade to the newest version of JSSImporter/python-jss.

**Comment by justinrummel** [comment]
These are going to both a file DP and JDS.  I can remove the JDS if it simplifies things.

Also, I believe I have the most current version of JSSImporter
``` 
sadmin@mo /L/A/autopkglib> cat JSSImporter.py | grep "__version__ =" | awk -F "'" '{print $2}'
0.3.6
```

**Comment by justinrummel** [comment]
Ok, Using Casper Admin I removed the latest Java 7.  Synced the change to the 2nd File DP.  Removed the JDS from AutoPkgr, ran ```autopkg run OracleJava7.jss --verbose``` and received: 

```
JSSImporter
JSSImporter: Category type: category-'Digital Media' already exists according to JSS, moving on...
JSSImporter: Category type: policy_category-'Auto Update' already exists according to JSS, moving on...
JSSImporter: Copying /Users/sadmin/Library/AutoPkg/Cache/local.jss.OracleJava7/OracleJava7-1.7.75.13.pkg to all distribution points.
JSSImporter: Copied /Users/sadmin/Library/AutoPkg/Cache/local.jss.OracleJava7/OracleJava7-1.7.75.13.pkg
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 1469, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 1463, in main
    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 1287, in run_recipes
    autopackager.process(recipe)
  File "/Library/AutoPkg/autopkglib/__init__.py", line 466, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 295, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 670, in main
    self.extattrs = self.handle_extension_attributes()
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 526, in handle_extension_attributes
    added_env="jss_extension_attribute_updated")
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 482, in _update_or_create_new
    self.j.put(url, recipe_object)
  File "/Library/Python/2.7/site-packages/python_jss-0.5.4-py2.7.egg/jss/jss.py", line 229, in put
    self._error_handler(JSSPutError, response)
  File "/Library/Python/2.7/site-packages/python_jss-0.5.4-py2.7.egg/jss/jss.py", line 174, in _error_handler
    raise exception
jss.exceptions.JSSPutError: JSS Error. Response Code: 409	Response" Conflict
Error: Duplicate name
```

**Comment by justinrummel** [comment]
The copy command completed:

```
sadmin@mo ~/L/A/RecipeOverrides> ll /Volumes/DataHD/CasperShare/Packages/ | grep OracleJava7
-rw-r--r--  1 casperadmin  staff    49M Oct 14 15:01 OracleJava7-1.7.71.14.pkg
-rw-r--r--  1 casperadmin  staff    49M Feb  7 16:20 OracleJava7-1.7.75.13.pkg
sadmin@mo ~/L/A/RecipeOverrides> ll /Volumes/DroboCasperShare/Packages/ | grep OracleJava7
-rw-r--r--  1 sadmin  staff    49M Oct 14 15:01 OracleJava7-1.7.71.14.pkg
-rw-r--r--  1 sadmin  staff    49M Feb  7 16:20 OracleJava7-1.7.75.13.pkg
```

**Comment by justinrummel** [comment]
It seems that the Extension attribute is giving some troubles.  If I remove the EA then run ```autopkg run OracleJava7.jss --verbose``` it works the first time.  Each subsequent run then produces an error regarding "handle_extension_attributes".

**Comment by homebysix** [comment]
[Sounds like](https://github.com/sheagcraig/JSSImporter/issues/25#issuecomment-73532123) this is an issue with JSSImporter or python-jss handling extension attributes correctly. I'm going to close it here, and Shea will open a new issue on one of those repos.

**Comment by sheagcraig** [comment]
Finally got a chance to take a peek at what is going on here.

When you specify that you'd like to make an extension attribute be part of your recipe, you specify an array of dicts; each dict describes one extension attribute.

The required keys for each EA are ```name``` and ```ext_attribute_path```. It seems logical that you should be able to specify a ```name``` here to be the name that shows up in the web interface. That's basically what it does; however, the name is specified a second place: in the templates ```computer_extension_attribute/name``` value.

If these two names don't match, you will get a response of 409 "Conflict" like above.

Please check and make sure that the two names are identical.

On my end, I don't see a reason to keep the ```name``` key around if it's already specified in the template. No string-replacement is happening to allow you to use any fancy dynamic variables or anything.

I have some open PR's for more control over various things via input variables, so while I review those, I'll audit the ease of use of the EA too.

Anyway, for the meantime, I'm pretty sure that's what's going on here.
