### ISSUE TITLE
Auto Update Magic runs the install policy even when firefox is running

### ISSUE THREAD

**Issue by charliwest** [homebysix/auto-update-magic#11]
Hi there,

First time testing this script today, I set it up for the firefox policy we already have and added the custom trigger autoupdate-Firefox and removed  Recurring Check-in. When I run it with firefox running it carries on the install anyway

    » ps aux | grep Firefox
    User           42584   0.0  1.5  3193336 256324   ??  S     3:12PM   0:05.25 /Applications/Firefox.app/Contents/MacOS/firefox
    User           51018   0.0  0.0  2432772    536 s003  S+    3:28PM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=.cvs --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn Firefox

    » sudo jamf policy
    Checking for policies triggered by "recurring check-in"...
    Executing Policy Auto Update Magic...
    Running script Auto_Update_Magic...
    Script exit code: 0
    Script result: Auto Update Magic has never run before. Checking for updates now...

    Checking for apps that would block the Firefox update...
    Firefox is not running.
    No apps are blocking the Firefox update. Calling policy trigger autoupdate-Firefox.
    Checking for policies triggered by "autoupdate-Firefox"...
    Executing Policy Install Latest Firefox...
    Downloading Firefox-35.0.1.pkg...
    This package is a PKG or an MPKG, and the index.bom file is not found. Attempting to open the package as a flat package...
    Downloading https://jds.mycompany.com/CasperShare/Firefox-35.0.1.pkg...
	Verifying package integrity...
	Installing Firefox-35.0.1.pkg...
	Successfully installed Firefox-35.0.1.pkg.
	Running Recon...
    Retrieving inventory preferences from https://jss.mycompany.com:8443/...
    Finding extension attributes...
    Locating accounts...
    Locating applications...
    Locating package receipts...
    Searching path: /Users
    Locating hard drive information...
    Locating software updates...
    Locating plugins...
    Searching path: /Library/Internet Plug-Ins
    Locating hardware information (Mac OS X 10.10.2)...
    Gathering application usage information...
    Searching path: /Applications
    Submitting data to https://jss.mycompany.com:8443/...
    <computer_id>302</computer_id>
    Submitting log to https://jss.mycompany.com:8443/
    Submitting log to https://jss.mycompany.com:8443/

Any ideas where I could be going wrong?

**Comment by homebysix** [comment]
Fascinating. You're not doing anything wrong at all. Here's the problem:

`ps ax | grep "Firefox" | grep -v grep` behaves as expected when Firefox is running. However `pgrep "Firefox"` produces no output. Other apps don't seem to have this problem. `pgrep "Google Chrome"` and `pgrep "Safari"` seem fine.

I may need to switch the script back to using `ps ax` instead of `pgrep` unless somebody knows of a solution to this issue.

**Comment by homebysix** [comment]
@charliwest I put an updated version of the script in the [pgrep-firefox](https://github.com/homebysix/auto-update-magic/tree/pgrep-firefox) branch, if you'd like to try it out.

If you can confirm that fixes the bug for you, I'll merge it into the master branch. Thanks!

**Comment by charliwest** [comment]
Newest one fixed it, thanks!
