### ISSUE TITLE
Remove Testing Criteria

### ISSUE THREAD

**Issue by justinrummel** [homebysix/auto-update-magic#13]
Reading https://github.com/homebysix/auto-update-magic#level-3-auto-to-all I assumed by modifying the SmartGroupTemplate.xml to exclude the "Testing" group requirement (thus leaving the "Application" and "Application Version" requirements only), I would then be able to see this change reflected in the Smart Groups.  However, this did not happen.

I then removed all existing Smart Groups thinking it was only going to change when creating the smart group vs. update, however each smart group was then replaced with the "Testing" group still required.  

What is creating the smart groups? Is there a way to have a global override, or will I need a per-app Override? 

``` xml
sadmin@mo ~/L/A/RecipeOverrides> pwd
/Users/sadmin/Library/AutoPkg/RecipeOverrides
sadmin@mo ~/L/A/RecipeOverrides> ll
total 112
-rw-r--r--  1 sadmin  staff   563B Dec 17 16:42 AdobeFlashPlayer.jss.recipe
-rw-r--r--  1 sadmin  staff    14K Dec 17 16:30 AdobeFlashPlayer.png
-rw-r--r--  1 sadmin  staff   591B Dec 17 16:36 AdobeFlashPlayerExtensionAttribute.xml
-rw-r--r--  1 sadmin  staff   612B Dec 17 16:42 AdobeFlashPlayerPolicyTemplate.xml
-rw-r--r--  1 sadmin  staff   362B Dec 18 07:39 AdobeFlashSmartGroupTemplate.xml
-rw-r--r--  1 sadmin  staff   626B Dec 17 16:43 AutoUpdatePolicyTemplate.xml
-rw-r--r--  1 sadmin  staff   605B Dec 17 16:43 AutoUpdateSmartGroupTemplate.xml
drwxr-xr-x  7 sadmin  staff   238B Feb  8 17:04 OracleJava7
-rw-r--r--  1 sadmin  staff   8.4K Jan 27 05:28 OracleJava7.tgz
-rw-r--r--  1 sadmin  staff   605B Feb 15 12:54 SmartGroupTemplate.xml
sadmin@mo ~/L/A/RecipeOverrides> cat SmartGroupTemplate.xml 
<computer_group>
    <name>%group_name%</name>
    <is_smart>true</is_smart>
    <criteria>
        <criterion>
            <name>Application Title</name>
            <priority>0</priority>
            <and_or>and</and_or>
            <search_type>is</search_type>
            <value>%JSS_INVENTORY_NAME%</value>
        </criterion>
        <criterion>
            <name>Application Version</name>
            <priority>1</priority>
            <and_or>and</and_or>
            <search_type>is not</search_type>
            <value>%VERSION%</value>
        </criterion>
    </criteria>
</computer_group>
```

**Comment by homebysix** [comment]
Hi @justinrummel! I'm sure this is a dumb question, but ~/L/A is short for ~/Library/AutoPkg, right? Otherwise I'd question whether the RecipeOverrides folder you're looking at is the actual folder AutoPkg is using.

Does `autopkg run GitHub.jss -vvv | grep SmartGroupTemplate` indicate that the correct SmartGroupTemplate.xml file is being used?

**Comment by justinrummel** [comment]
@homebysix you are correct in ~/L/A is short for ~/Library/AutoPkg.  I use http://fishshell.com and it will shorten the path. 

The OracleJava7 is a directory (to keep things organized), and inside that folder is: 
``` bash
sadmin@mo ~/L/A/R/OracleJava7> ll
total 48
-rw-r--r--  1 sadmin  staff   518B Jan 26 19:48 OracleJava7.jss.recipe
-rw-r--r--  1 sadmin  staff   7.0K Jan 26 19:57 OracleJava7.png
-rw-r--r--  1 sadmin  staff   576B Feb  8 17:05 OracleJava7ExtensionAttribute.xml
-rw-r--r--  1 sadmin  staff   620B Jan 26 20:32 OracleJava7PolicyTemplate.xml
-rw-r--r--  1 sadmin  staff   365B Feb  8 17:11 OracleJava7SmartGroupTemplate.xml
```

**Comment by justinrummel** [comment]
OracleJava7SmartGroupTemplate.xml is being used when running ```autopkg run OracleJava7.jss -vvv```
``` xml
        name = "OracleJava7-update-smart";
        smart = 1;
        "template_path" = "/Users/sadmin/Library/AutoPkg/RecipeOverrides/OracleJava7/OracleJava7SmartGroupTemplate.xml";
```

**Comment by homebysix** [comment]
Here's the `OracleJava7SmartGroupTemplate.xml` I'm using. Does yours match this?
```xml
<computer_group>
    <name>%group_name%</name>
    <is_smart>true</is_smart>
    <criteria>
        <criterion>
            <name>OracleJavaVersion</name>
            <priority>0</priority>
            <and_or>and</and_or>
            <search_type>is not</search_type>
            <value>%VERSION%</value>
        </criterion>
        <criterion>
            <name>OracleJavaVersion</name>
            <priority>0</priority>
            <and_or>and</and_or>
            <search_type>not like</search_type>
            <value>1.8</value>
        </criterion>
        <criterion>
            <name>OracleJavaVersion</name>
            <priority>0</priority>
            <and_or>and</and_or>
            <search_type>is not</search_type>
            <value></value>
        </criterion>
    </criteria>
</computer_group>
```

**Comment by justinrummel** [comment]
No.  It seems like some of it was cut off.  I'll copy/paste your settings to see if this helps.

**Comment by justinrummel** [comment]
I'll see what happens on the next release of Java (is that on Tuesdays?).  However, I'm still getting the "handle_extension_attributes" and an issue has already been created for that: https://github.com/sheagcraig/JSSImporter/issues/26

**Comment by homebysix** [comment]
@justinrummel - Did that get fixed for you on the JSSImporter end?

**Comment by justinrummel** [comment]
Hello Elliot, I have dropped trying to figure this out as I'm no longer in the MacAdmin scene for my employment.  You can close this issue.
