### ISSUE TITLE
Launch AutoPkgr at login...

### ISSUE THREAD

**Issue by jtrappey** [homebysix/auto-update-magic#14]
Having trouble getting the "launch at login" working.

I've installed Autopkgr v. 1.2 on a mac running Yosemite 10.10.2. This mac is talking to our JSS running on a Windows VM with Casper v. 9.63. 

When trying to check the box for "Launch AutoPkgr at login", the box flashes as if its checked then unchecks. Checking the logs doesn't seem to show any related clues.

**Comment by homebysix** [comment]
Hi @jtrappey, you may want to take a look at this issue at the AutoPkgr GitHub repo:
https://github.com/lindegroup/autopkgr/issues/272

If you have any further questions, please open an issue on AutoPkgr, not auto-update-magic. Thanks!
