### ISSUE TITLE
Casper Admin package populates in red and indicates package is missing.

### ISSUE THREAD

**Issue by jimmymac641** [homebysix/auto-update-magic#15]
Attempting to run Level 1 "Testing" with the Self Service option and all seems to work quite nicely except the package I'm testing with "Handbrake" is imported into the Casper Admin and appears as a red entry and under the "type" column header shows up as "missing". Therefore when the Self Service install is attempted the jss reports an error of failure to complete install and to contact administrator.

Any suggestions as to why this may be happening?

**Comment by homebysix** [comment]
Hi @jimmymac641 — do you have the latest version of all the components? AutoPkg, AutoPkg, JSSImporter, and python-jss?

I've seen this before when the master DP is a JDS. Uploading files to Casper Admin and then immediately quitting Casper Admin (before the uploaded file has a chance to be "processed" by the JSS) results in the same behavior. I'm not sure how to fix that yet, but making sure you have the latest components is a good first step.

**Comment by jimmymac641** [comment]
@homebysix AutoPkg = 0.4.2, AutoPkgr = 1.2.1(726), JSSImporter = 0.3.6, python-jss = 0.5.6. No JDS instances at all. The Casper Admin remains launched at all times unless I want to check the import then I manually do a save, quit and relaunch. Package appears but remains in red and type remains missing.

**Comment by homebysix** [comment]
Make sure not to run Casper Admin while AutoPkg/AutoPkgr is doing its thing. Otherwise they fight over who gets to mount the distribution point, and one of them loses.

**Comment by homebysix** [comment]
Hi @jimmymac641, python-jss version 0.5.7 and later now check to ensure the distribution points are not already mounted before trying to mount again.

With the latest versions of everything, is this still happening for you?
