### ISSUE TITLE
Error when trying to re run workflow

### ISSUE THREAD

**Issue by mtaylor934** [homebysix/auto-update-magic#16]
Hi there,

Just investigating the Self Service safe method and was able to get it working.  Had a few questions / issues:

1)  The username and password required for the JSSImporter, does this account also need to exist in AD with read/write permissions for the DP?
2)  Successfully ran the workflow for one Adobe Flash Player package.  I ticked 10 more .jss recipes and tried to run again, but then get an error detailing object already exists.  Cleared JSS of anything related (except Testing group) and still get the error.  Have included it below.  Will this happen every time unless each package has an update?

But apart from the above, this is an absolutely brilliant workflow.  Kudos to everyone who contributed!

![image](https://cloud.githubusercontent.com/assets/11530159/6700694/834e23b0-cd65-11e4-8be2-7da87c0c3953.png)

**Comment by homebysix** [comment]
Hi @mtaylor934 - are you still having this trouble? JSSImporter and AutoPkgr have both had significant updates recently, so it might be worth trying again with new versions. If you're still having trouble let me know and I'll investigate.
