### ISSUE TITLE
Cache if running, install on logout

### ISSUE THREAD

**Issue by charliwest** [homebysix/auto-update-magic#18]
Another idea for an enhancement.
If the app is running cache the pkg, then on log out (or other) the package can be installed. Or possibly a pop up "Hey you always have X application running so I can never update it, how about you let me close it and update it for you now. Please."
Similar to how patchoo does?

**Comment by homebysix** [comment]
"Cache if running, install on logout" should be possible. You'd need the following:

- An override for Application.jss that creates a policy that caches the latest version of the app installer.
- A copy of PolicyTemplate.xml, used by the above override, that includes `<action>Cache</action>` in the `<packages>` section.
- An override for Application.jss that creates a policy that installs the cached installer at logout.
- A copy of PolicyTemplate.xml, used by the above override, that includes `<trigger_logout>true</trigger_logout>` in the `<general>` section.

The pop up that asks users to quit the application is a good idea, and Patchoo does it well I think. It's outside the scope of "auto update magic" though.
