### ISSUE TITLE
Change the checking logic

### ISSUE THREAD

**Issue by charliwest** [homebysix/auto-update-magic#19]
I have noticed as I grow auto-update-magic to update more and more apps we seem to be running into problems with slow down of the machines, I am not 100% sure its AUM causing it, but it does seem to be. It got me thinking about the checking logic though and I wonder if it might be better to think about about from the other side, using the API check what APPLICATION-update-smart it is part of, then run through the blocking apps for only those groups, then run the policy. 

Does that make sense?

**Comment by homebysix** [comment]
Hi @charliwest — There's a big update to Auto Update Magic in the works, and I'd love to have you test it out and tell me whether the performance has changed since version 1.0. Interested?

**Comment by charliwest** [comment]
Yeah sure no worries
