### ISSUE TITLE
Recipe names now contain spaces

### ISSUE THREAD

**Issue by pereljon** [homebysix/auto-update-magic#20]
Hey Elliot,

Noticed that there's a comment in the script which states that recipe names don't typically contain spaces. Hasn't this changed now? Does it affect the script or does the comment need to be updated?

Cheers,
JP
/# Add a line here for each auto-update recipe name. Recipe names do not
/# typically contain spaces. Some examples are included below:

**Comment by homebysix** [comment]
Hi @pereljon! Yes indeed. The new version I'm working on replaces `Recipe names do not typically contain spaces` with `Recipe names may contain spaces` thanks to the recent move to put spaces into jss recipe filenames and path.

I'm confident everything is escaped properly, so adding spaces should work even in v1.x of the script.
