### ISSUE TITLE
Incorrect blocking on process subname

### ISSUE THREAD

**Issue by pereljon** [homebysix/auto-update-magic#23]
Hey there,

The auto_update_magic.sh script is blocking incorrectly when a process exists whose name has a substring which is the name of a blocking process . For example, if I'm blocking on "Safari" for the update trigger "AdobeFlashPlayer", the script will block when Safari is not running, but the following processes are running:
 >1445   ??  U      1:46.44 /usr/libexec/SafariCloudHistoryPushAgent
 >1470   ??  Ss     0:00.05 /System/Library/PrivateFrameworks/SafariServices.framework/Versions/A/XPCServices/com.apple.SafariServices.xpc/Contents/MacOS/com.apple.SafariServices
>50673   ??  Ss     0:00.07 /System/Library/PrivateFrameworks/SafariServices.framework/Versions/A/XPCServices/com.apple.SafariServices.xpc/Contents/MacOS/com.apple.SafariServices

The fix here is to change the `pgrep` to `pgrep -x`, as the default behavior of pgrep is to "match any substring", and the -x requires an exact match of the process name.

Also, you could add the -i flag and make it case-insensitive, and you'd be able to ditch the `APP_CLEAN_LOWER` code.

Cheers,
JP

**Comment by homebysix** [comment]
Incredibly helpful, thank you! I'll make those changes soon.
