### ISSUE TITLE
[Exercise 5c] Safari is always running in 10.11, blocking apps from autoupdating

### ISSUE THREAD

**Issue by rougegoat** [homebysix/auto-update-magic#25]
I started setting this auto-update check up in my environment on a test machine.  I noticed that when every program was closed, anything that had Safari as a blocking program would not work as expected.  So I ran "pgrep Safari" and discovered that when Safari is closed, there are two processes running in the background under it.  OS X auto-starts these when they're killed, so they should be assumed to be always in place.  As a result of these two processes, Safari is always treated as running even if the program has been quit.

Fortunately, the three examples that used Safari as a blocking app no longer require Safari be closed while they install.  This means it can be removed from their blocking list without issue.  It's a minor tweak that should fix the issue.

**Comment by homebysix** [comment]
Thanks @rougegoat. You may also find that using `Safari$` as the blocking app string will fix that issue. I do a similar thing for Evernote, in order to prevent the Evernote Helper app from blocking updates.
