### ISSUE TITLE
Defaults write command throws error

### ISSUE THREAD

**Issue by charliwest** [homebysix/auto-update-magic#27]
In the last commit you edited this line 

`/usr/bin/defaults write "$PLIST" LastAutoUpdate -date "$(date +%s)"`

When I run this it gives me an error

> + /usr/bin/defaults write '/Library/Application Support/JAMF/com.jamfsoftware.jamfnation' LastAutoUpdate -date 1466415856
Command line interface to a user's defaults.
Syntax:
'defaults' [-currentHost | -host <hostname>] followed by one of the following:

I have played around and kind of fixed it
    `current=$(date +"%Y-%m-%d %l:%M:%S +0000") 
    # Record the timestamp of the last auto update check.
    if [[ $DEBUG_MODE == false ]]; then
    /usr/bin/defaults write "$PLIST" LastAutoUpdate -date "$current"
    fi`

Although could be fixed in other ways depending on what date stamp you want.

**Comment by homebysix** [comment]
Oops, thanks for catching that! I forgot to remove the `+%s`.
