### ISSUE TITLE
Update to auto_update_magic.sh script for version 1.0

### ISSUE THREAD

**Issue by lakem** [homebysix/auto-update-magic#28]
Just to let you know, in the auto_update_magic.sh in version 1.0, you still have the policy trigger at the bottom of the script (line 126), set to "/usr/sbin/jamf -trigger "autoupdate-${RECIPE_NAME[$i]}"". However, it will now need to be "/usr/local/jamf/bin/jamf policy -trigger "autoupdate-${RECIPE_NAME[$i]}"" in order to work.

I've not tried version 2.0 just yet, as I did like the convenience of version 1.0 using the scrip via Policy.

Keep up the good work. It's the good guys like you, that make life as a sys. admin that little bit better. Many thanks

**Comment by homebysix** [comment]
You're very welcome! 😄 

Version 1.0 is a sort of "snapshot in time," and I have no plans to keep it updated. But if you're still using the script via policy, you can probably put [these lines](https://github.com/homebysix/auto-update-magic/blob/master/Exercise5c/auto_update_magic.sh#L89-L95) into the old version of the script.

Depending on what JAMF releases in the near future, I may take a shot at a version 3.0 of Auto Update Magic. No promises, though. ;-)

**Comment by lakem** [comment]
Great stuff. When I feel more comfortable with the setup, I will consider moving over to v2.0. Loving it so far. Thanks again.
