### ISSUE TITLE
Provide Adobe Flash Player script template which checks for running browsers before updating

### ISSUE THREAD

**Issue by homebysix** [homebysix/auto-update-magic#3]

**Comment by charliwest** [comment]
Just out of interest wouldn't that just be a case of adding the blocking programs?

**Comment by homebysix** [comment]
Exactly. I'm just keeping this open until I actually post a script that shows that happening.

**Comment by homebysix** [comment]
Turns out this doesn't work, because we're using pgrep:
```bash
RECIPE_NAME=(
    "AdobeFlashPlayer"
)
BLOCKING_APPS=(
    ""
)
```

However, you can do this by specifying a blocking app that doesn't (and never will) exist:
```bash
RECIPE_NAME=(
    "AdobeFlashPlayer"
)
BLOCKING_APPS=(
    "NoBlockingAppNecessaryForAdobeFlashPlayer"
)
```
I think that's sufficient for now.
