### ISSUE TITLE
JSS Importer - Issues with Site

### ISSUE THREAD

**Issue by bandoned** [homebysix/auto-update-magic#32]
I've been successfully using AutoPkgr with Sites by manually specifying the Site ID and name in the SmartGroupTemplate and PolicyTemplates in AutoPkgr. So as long as you keep using groups/objects in the same site you are creating a policy for everything is working great.

However, lately some apps we need to deploy on both sites. For this, Autopkgr does not seem to accept Site ID "-1" and name "None" if one of the Computer Groups/Object being scoped to is in a site.

On the JSS interface doing this working completely fine. Would it be possible to fix this? This is probably some check that was thrown in that is assuming if a site is specified then it only works with Computer Groups that are in that particular site. Which is true, except when the site is "None". In which case, the policy can access Groups/Objects in any site.

For now the workaround is to create 2 different entries, one that would create a Policy for Site A and another that would create a Policy for Site B. But this means you loose the ability to have policies that Site administrators cannot modify, that are for the entire system.

**Comment by homebysix** [comment]
Hi @bandoned. I have two initial thoughts:

- Have you tried omitting the site ID from the template entirely? I don't use sites, but it seems logical to me that any policy template that does not include site information would be created with the site set to "None."
- If you're having trouble creating policies, packages, or groups, you're more likely to get traction by submitting an issue to the [JSSImporter repository](https://github.com/sheagcraig/JSSImporter/issues). AutoPkgr is just a UI that allows configuring JSSImporter and running JSS recipes, but does not know or care about the details of which policy is using which site. And Auto Update Magic is just a series of workflow examples that use JSSImporter.

I'll keep this issue open until the first bullet is answered, but I think you'll need to ask elsewhere about the second bullet. Thanks!

**Comment by bandoned** [comment]
@homebysix I will definitely do that. Thanks

Yes, I did try removing the Site ID instead of setting it to None first. But seems like it detects one of the groups that the policy is being scoped to is in a site it throws an error.

`Response Code: 409	Response: Conflict. Error: ComputerGroup (ID:62, Name:SiteB-SmartGroup) is not site-enabled for this site`

This was scoped to two groups, SiteA-SmartGroup and SiteB-SmartGroup

**Comment by homebysix** [comment]
Well, you're beyond my wheelhouse. I've never found the added complexity of Sites has been worth it.

**Comment by homebysix** [comment]
Closing due to repo deprecation and archival.
