### ISSUE TITLE
Intermittent issue with some iLife and iWork Apps

### ISSUE THREAD

**Issue by jwzg** [homebysix/auto-update-magic#7]
Take a look at the log entries below: seems to be an issue with the _MASReceipt creation.  

12/5/14 3:11:14.550 PM AutoPkgr[94154]: (FULL AUTOPKG TRACEBACK) 
  File "/usr/local/bin/autopkg", line 1334, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 1328, in main
    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 1152, in run_recipes
    autopackager.process(recipe)
  File "/Library/AutoPkg/autopkglib/__init__.py", line 466, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 295, in process
    self.main()
  File "/Users/configurator/Library/AutoPkg/RecipeRepos/com.github.autopkg.scriptingosx-recipes/AppleCreativity/MASReceipt.py", line 61, in main
    os.rmdir(masreceipt_dir_path)
OSError: [Errno 2] No such file or directory: '/Users/configurator/Library/AutoPkg/Cache/com.github.scriptingosx.pkg.iMovie/iMovie/Applications/iMovie.app/Contents/_MASReceipt'
12/5/14 3:11:14.706 PM secd[855]:  securityd_xpc_dictionary_handler AutoPkgr[94154] copy_matching The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
12/5/14 3:11:14.706 PM AutoPkgr[94154]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))

**Comment by homebysix** [comment]
Hi @jwzg,

I think this issue is more appropriate for the recipe authors. I don't think it's related to my Auto Update Magic workflow.

Thanks,

Elliot
